/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/orders": {
    /**
     * Orders
     * @description Get all DEXs orders
     */
    get: {
      responses: {
        /** @description Orders */
        200: {
          content: {
            "application/json": components["schemas"]["Order"][];
          };
        };
        /** @description Not found */
        404: {
          content: {
            "text/html": string;
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Order: {
      id?: number;
      tx_id?: string;
      tx_index?: number;
      slot?: number;
      timestamp?: string;
      dex_type?: string;
      order_type?: string;
      cancelled?: boolean;
      metadata_msg?: string;
      sender_payment_vkey?: string;
      sender_address?: string;
      receiver_payment_vkey?: string;
      receiver_address?: string;
      asset_a?: string;
      asset_b?: string;
      amount_a?: string;
      amount_b?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
